name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  yarn-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - run: yarn install
      - run: yarn frontend

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install flake8
      - run: make lint-minimal

  build:
    runs-on: ubuntu-latest
    needs: [yarn-frontend]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install wheel
      - run: python setup.py bdist_wheel
      - uses: actions/upload-artifact@v1
        with:
          name: bdist-wheel-package
          path: dist

  make-docs:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: bdist-wheel-package
          path: packages
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install sphinx
      - run: pip install $(find packages -name "*.whl")
      - run: non_interactive=1 make docs


  sphinx-quickstart:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download wheel
        uses: actions/download-artifact@v1
        with:
          name: bdist-wheel-package
          path: packages
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install sphinx
      - run: pip install $(find packages -name "*.whl")
      - name: Sphinx quickstart
        run: |
          html_theme=sphinx_wagtail_theme
          sphinx-quickstart --project PROJECT --author AUTHOR --sep \
             --extensions ${html_theme} --no-use-make-mode --quiet
          echo >> source/conf.py
          echo 'extensions.append("'${html_theme}'")' >> source/conf.py
          echo 'html_theme = "'${html_theme}'"' >> source/conf.py
          echo 'source/conf.py'
          cat source/conf.py
      - name: Sphinx build
        run: |
          sphinx-build -b html -A version=faked/offline source build
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: sphinx-quickstart
          path: build


  make-test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download wheel
        uses: actions/download-artifact@v1
        with:
          name: bdist-wheel-package
          path: packages
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install --upgrade pip pytest twine
      - run: pip install -e .
      - name: Assert is importable, show version
        run: python -c "import sphinx_wagtail_theme; print(sphinx_wagtail_theme.__version__)"
      - run: pytest
      - name: make test TODO Make this work
        if: 0
        run: make test
      - run: twine check packages/*
